name: CI 

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

env:
  TRAIN_FILE: "MLproject/X_train.csv"
  TEST_FILE: "MLproject/X_test.csv"
  YTRAIN_FILE: "MLproject/y_train.csv"
  YTEST_FILE: "MLproject/y_test.csv"

jobs: 
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps: 
    - uses: actions/checkout@v3

    # setup python 3.12.7
    - name: Set up python 3.12.7
      uses: actions/setup-python@v4
      with: 
        python-version: "3.12.7"

    # Check env variables
    - name: Check Env
      run: |
        echo "TRAIN_FILE=$TRAIN_FILE"
        echo "TEST_FILE=$TEST_FILE"
        echo "YTRAIN_FILE=$YTRAIN_FILE"
        echo "YTEST_FILE=$YTEST_FILE"

    # Install mlflow
    - name: install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install mlflow

    # run as a mlflow project
    - name: Run mlflow project
      run: |
        mlflow run MLproject --env-manager=local

    # Save model to Github Repository
    # Save models to GitHub Repository
    - name: Save mlruns to repo
      run: |
        git config --global user.name ${{ secrets.GIT_USERNAME }}
        git config --global user.email ${{ secrets.GIT_EMAIL }}
        git add mlruns/
        git commit -m "Save mlruns from CI run"
        git push -u origin main

    
