name: CI 

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

env:
  TRAIN_FILE: "MLproject/X_train.csv"
  TEST_FILE: "MLproject/X_test.csv"
  YTRAIN_FILE: "MLproject/y_train.csv"
  YTEST_FILE: "MLproject/y_test.csv"

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    # setup python 3.12.7
    - name: Set up python 3.12.7
      uses: actions/setup-python@v4
      with: 
        python-version: "3.12.7"

    # Check env variables
    - name: Check Env
      run: |
        echo "TRAIN_FILE=$TRAIN_FILE"
        echo "TEST_FILE=$TEST_FILE"
        echo "YTRAIN_FILE=$YTRAIN_FILE"
        echo "YTEST_FILE=$YTEST_FILE"

    # Install mlflow
    - name: install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install mlflow

    # run as a mlflow project
    - name: Run mlflow project
      run: |
        mlflow run MLproject --env-manager=local

    # Save model to Github Repository
    - name: Commit and Push MLflow Results
      run: |
        git config --global user.name ${{ secrets.GIT_USERNAME }}
        git config --global user.email ${{ secrets.GIT_EMAIL }}
        git lfs install
        git lfs track "*.pkl"
        git add .gitattributes
        git add -f MLproject/mlruns/
        if git diff --staged --quiet; then
          echo "No new changes to commit."
        else
          git commit -m "Save mlruns from CI run [skip ci]"
          git push origin main
        fi

    
